## Working with DataFrames
-

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("employee.csv")
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

## Column Selection in Pandas
- df["column_name"]
- df.Column_name 
- a single column will exist as a series object
- 
- df[data] - this indexing method will take a single argument --- a `string` or a `list`
    - what if we need multiple columns
    -

In [48]:
# acessing columns in the dataframe
# access columns by --- Name
df['Name']
df.Name # only one column


columns = ["Name","Salary",	"Experience"]
df[columns]

# subset of dataframe
df_salary = df[["Salary",	"Experience"]]
display(df_salary)

#df["Name","Salary"] # will not work

   Salary  Experience
0   75000           3
1   65000           5
2   80000           7
3   60000           2
4   70000           4

In [49]:
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering   75000           3
1      Bob    Marketing   65000           5
2  Charlie  Engineering   80000           7
3    Diana           HR   60000           2
4      Eve    Marketing   70000           4

## Selection using the Location or Labels
##### integer Location --- **.iloc[]**
- `df.iloc[row index]` # access rows
- 
- `df.iloc[row_index_slice]` # [start: end : stepsize]
- INDEXING ----
- `df.iloc[row_slice, column_slice]`
-

In [50]:
df.iloc[0] # first row as a series object

df.iloc[-1] # last row

df.iloc[1:3] # rows from 1 upto 3

df.iloc[1:4:2] # in steps of 2

# ---- indexing works

df.iloc[:4, 1:3] #first 4 rows, 

df.iloc[[0,2,3], [0,2,3]] # you can access the rows, columns by number, but
# if out of index, error will be thrown
# errors are not thrown if you are accessing using slices

      Name  Salary  Experience
0    Alice   75000           3
2  Charlie   80000           7
3    Diana   60000           2

In [51]:
# i want the data of the last two entries, for department and experience
df.iloc[-2:,[1,3]]

  Department  Experience
3         HR           2
4  Marketing           4

#####  Label - .loc[]
- focuses on labels
- df.loc[0:3] # targets the names of these rows
- Which are the indexes
-

In [52]:
# 
ind = ['a','b','c','d','e']
df = pd.read_csv("employee.csv")
df['index'] = ind

df = df.set_index('index')
display(df)
# -----
df.index = ['a','b','c','d','e']
display(df)

          Name   Department  Salary  Experience
index
a        Alice  Engineering   75000           3
b          Bob    Marketing   65000           5
c      Charlie  Engineering   80000           7
d        Diana           HR   60000           2
e          Eve    Marketing   70000           4

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [53]:
df.loc[0] # row
df.loc[0:3] # slice of rows

# df.loc[0:3, 0:3] # throws an error

df.loc[0:3, ['Department', 'Experience']]

KeyError: 0

In [ ]:
df.loc['a':'d', 'Department':'Experience':2]

        Department  Experience
index
a      Engineering           3
b        Marketing           5
c      Engineering           7
d               HR           2

In [ ]:
df = pd.read_csv("employee.csv")

df.index = ("a","b","c","d","e")
 
df

      Name   Department  Salary  Experience
a    Alice  Engineering   75000           3
b      Bob    Marketing   65000           5
c  Charlie  Engineering   80000           7
d    Diana           HR   60000           2
e      Eve    Marketing   70000           4

In [ ]:
df.index
df.columns

Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')

1. Create an account on Kaggle - Explore Kaggle
2. Play with the World Cup file
3. Create account on Hugging Face too

### Adding and Modifying Columns
-

In [54]:
# adding a column
# access a column that does not exist
df['email'] = ['alice@gmail.com','Bob@gmail.com','charlie@gmail.com','diana@gmail.com','eve@gmail.com']
df

# modify a column
list(df['Department']) 

df['Department'] = ['Engineering', 'Marketing', 'Physics', 'HR', 'Marketing']

# use modify all elements of a column --- in one go 
df.Salary = df.Salary/1000 # Scaling operation
# took the column and scaled it down

df.Experience = df.Experience +1
df

      Name   Department  Salary  Experience              email
a    Alice  Engineering    75.0           4    alice@gmail.com
b      Bob    Marketing    65.0           6      Bob@gmail.com
c  Charlie      Physics    80.0           8  charlie@gmail.com
d    Diana           HR    60.0           3    diana@gmail.com
e      Eve    Marketing    70.0           5      eve@gmail.com

In [57]:
# modfying a value
# df['Department']['d'] = 'Crime Analytics'

df.loc['d','Department'] = 'Crime Analytics'

df.iloc[3, 1] = 'Linguistics'
df

      Name   Department  Salary  Experience              email
a    Alice  Engineering    75.0           4    alice@gmail.com
b      Bob    Marketing    65.0           6      Bob@gmail.com
c  Charlie      Physics    80.0           8  charlie@gmail.com
d    Diana  Linguistics    60.0           3    diana@gmail.com
e      Eve    Marketing    70.0           5      eve@gmail.com

### EDA (Exploratory Data Analysis) with Pandas
- Some methods that we can run on dataframes
- Basic Inspection methods:
    - `df.head()` - give you the first 5 elements
        - an argument of 10 will give you first 10 elements
    - df.tail() - last 5 but argument can change the number
    - `df.sample()` - one random entry from the dataset
        - an argument can change that number too 
        - we use this to check how our datasets look like inside
- Basic attributes of a dataframe:
    - `df.shape` - tells you the shape of the df --- how many elements along how many axes
    - df.size - how many elements there are
    - df.ndim - will tell you the number of axes there are in the df --- generally just 2
    - `df.dtypes` - will tell you the data type of each column



- Methods for Statistical information as well:
    - `df.info()` - general information about the df
        - how many records, how many columns, what is the data type of those columns
        - also gives an idea of if there are any missing values in data
    - `df.describe()` - gives us the statistical measurements of the columns like count, mean, min, max, std, percentiles 
-

In [86]:
df.head(10)
df.tail()
df.sample(4)

df.shape
df.size 
df.dtypes

df.info()

df.describe()

<class 'pandas.DataFrame'>
Index: 5 entries, a to e
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Department  5 non-null      str
 2   Salary      5 non-null      float64
 3   Experience  5 non-null      int64
 4   email       5 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 412.0+ bytes

          Salary  Experience
count   5.000000    5.000000
mean   70.000000    5.200000
std     7.905694    1.923538
min    60.000000    3.000000
25%    65.000000    4.000000
50%    70.000000    5.000000
75%    75.000000    6.000000
max    80.000000    8.000000

Exercise:
- Please go to Kaggle
- Download this dataset: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially the EDA that we learnt about in today's class on it

## Filtering

## Aggregation

## Grouping